
### Добавление события RCHP

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "",
  "location": "",
  "price": 100
}

### Добавление события Lenny Kravitz

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "Lenny Kravitz Concert",
  "location": "Berlin",
  "price": 150
}

### Получение всех событий

GET localhost:8080/api/events

### Удаление события

DELETE localhost:8080/api/events/1

### Обновление события

PUT http://localhost:8080/api/events/1
Content-Type: application/json

{
  "newName" : "Metallica",
  "newLocation" : "Singen",
  "newState" : "IN_PROGRESS"
}

### Получаем одно событие

GET http://localhost:8080/api/events/1






