INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE)
VALUES ('Abu-Bakar.Musayev@gmail.com', 'qwerty007', 'USER');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE)
VALUES ('Albina.Arushanian@yahoo.com', 'qwerty008', 'USER');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE)
VALUES ('Dmytro.Sainozhenko@bing.com', 'qwerty009', 'MANAGER');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE)
VALUES ('Edgar.Arushanyan@email.com ', 'qwerty010', 'USER');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE)
VALUES ('Ekaterina.Zakozhurnikova@icloud.com', 'qwerty011', 'MANAGER');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE)
VALUES ('Irene.Steitz@mail.de', 'qwerty012', 'USER');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE)
VALUES ('Joseph.Hafizi@mail.de', 'qwerty013', 'USER');

INSERT INTO TASK (DESCRIPTION, FINISH_DATE, START_DATE, TITLE, EXECUTOR_ID, STATE) VALUES ('Task 1 description', '2023-12-12', '2023-11-11', 'Task 1', 2, 'DRAFT');
INSERT INTO TASK (DESCRIPTION, FINISH_DATE, START_DATE, TITLE, EXECUTOR_ID, STATE) VALUES ('Task 2 description', '2024-12-12', '2023-11-10', 'Task 2', 3, 'PUBLISHED');
INSERT INTO TASK (DESCRIPTION, FINISH_DATE, START_DATE, TITLE, EXECUTOR_ID, STATE) VALUES ('Task 3 description', '2023-11-09', '2023-09-12', 'Task 3', 1, 'PUBLISHED');
INSERT INTO TASK (DESCRIPTION, FINISH_DATE, START_DATE, TITLE, EXECUTOR_ID, STATE) VALUES ('Task 4 description', '2025-03-04', '2025-01-01', 'Task 4', 4, 'PUBLISHED');
INSERT INTO TASK (DESCRIPTION, FINISH_DATE, START_DATE, TITLE, EXECUTOR_ID, STATE) VALUES ('Описание задачи 1', '2025-01-01', '2024-01-02', '1', 1, 'DELETED');
INSERT INTO TASK (DESCRIPTION, FINISH_DATE, START_DATE, TITLE, EXECUTOR_ID, STATE) VALUES ('Описание задачи 1', '2025-01-01', '2024-01-02', '1', 1, 'DRAFT');

