### Добавление пользователя 1

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "Marsel@gmail.com",
  "password": "Qweerty123!"
}

### Добавление пользователя 2

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "alisher@gmail.com",
  "password": "Hello006!"
}


### Получение всех пользователей

GET localhost:8080/api/users?orderBy=email&desc=true&page=0&filterBy=state&filterValue=CONFIRMED
### Добавление задачи 1

POST localhost:8080//api/users/1/tasks
Content-Type: application/json

{
  "title" : "1",
  "description" : "Описание задачи 1",
  "startDate": "2024-01-02",
  "finishDate": "2025-01-01"
}

### Добавление задачи 2

POST localhost:8080//api/users/1/tasks
Content-Type: application/json

{
  "title" : "2",
  "description" : "Описание задачи 2",
  "startDate": "2022-01-02",
  "finishDate": "2025-01-02"
}

### Добавление задачи 3

POST localhost:8080//api/users/2/tasks
Content-Type: application/json

{
  "title" : "Задача 3",
  "description" : "Описание задачи 3",
  "startDate": "2024-01-02",
  "finishDate": "2024-01-22"
}

### Получение всех задач пользователя 1

GET localhost:8080/api/users/1/tasks/published?page=0

### Получение всех задач пользователя 2

GET localhost:8080/api/users/2/tasks?page=0

### Получение всех задач

GET localhost:8080/api/tasks?orderBy=title&desc=true&page=1
### Получение всех задач

GET localhost:8080/api/tasks?page=0

### Обновление пользователя 1

PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "newRole" : "MANAGER",
  "newState" : "BANNED"
}

### Получение пользователя с задачами
GET localhost:8080/api/users?tasks=published&page=0

### Получить все опубликованные задачи определенного пользователя

GET http://localhost:8080/api/users/1/tasks/published?page=0

