### Добавление пользователя 1

POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### Добавление пользователя 2

POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "alisher@gmail.com",
  "password": "hel"
}


### Получение всех пользователей

GET localhost:8080/users

